/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.filtroArq;
import dataManipulation.saveBin;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pittigliani
 */
public class abreArq extends javax.swing.JDialog {

    JFileChooser chooser = new JFileChooser();

    /**
     * Creates new form abreArq
     */
    public abreArq(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         filtroArq filter = new filtroArq();
         chooser.setFileFilter(filter);
         chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);//J FILE CHOOSER aceita apenas arquivos
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar arquivo");

        jButton1.setText("Abrir arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setBounds(0, 0, 185, 130);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int result = chooser.showOpenDialog(null);
        if (result == chooser.APPROVE_OPTION) {
            //  File f = chooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Arquivo selecionado");
            this.dispose();
            saveBin sb = new saveBin();
            try {
                if (sb.leCSV(chooser.getSelectedFile().getCanonicalPath()) == 1) {
                    Principal p = new Principal();
                    sb = null;
                    p.setLocationRelativeTo(null);
                    p.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao ler o arquivo.");
                }
            } catch (IOException ex) {
                Logger.getLogger(abreArq.class.getName()).log(Level.SEVERE, null, ex);
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
